[package]
name = "rust-learning"
version = "0.1.0"
authors = ["chenglong.wang <tiny.wcl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
unicode-segmentation = "1.6.0"
lazy_static = "1.4.0"
rand = "0.7.3"
futures = "0.3.4"