pub mod acronym;
pub mod clock;
pub mod difference_of_squares;
pub mod high_scores;
pub mod matching_brackets;
pub mod nth_prime;
pub mod reverse_string;
pub mod simple_linked_list;
pub mod binary_search;